/**
 * @file equiripple_filter.h
 * @author FernandesKA (fernandes.kir@yandex.ru)
 * @brief Equiripple (Parks-McClellan) anti-aliasing + decimation filter for the IQ path
 * @version 0.1
 * @date 2026-07-17
 *
 * @copyright Copyright (c) 2026
 *
 */

#pragma once

#include <complex>
#include <cstddef>
#include <vector>

#include "dsp/resampler.h"

namespace dsp {

    // Combined anti-aliasing low-pass + decimation stage for the IQ path
    // (2 MHz capture -> 200 kHz channel rate). Coefficients are equiripple
    // (Parks-McClellan), generated by matlab/lpf_synth.m into
    // inc/dsp/filters/lowpass_2m_to_200k.hpp - fixed at compile time since
    // the capture sample rate itself is fixed (config::hackrf_sample_rate_hz),
    // so there's nothing to recompute at runtime.
    //
    // Only every Dth input sample triggers a FIR dot product (the samples in
    // between are only needed to keep the delay line/history correct), so
    // this does not waste work on output points decimation discards.
    class equiripple_filter final : public resampler<std::complex<float>> {
    public:
        equiripple_filter();

        void process(const std::complex<float> *in, std::size_t count,
                     std::vector<std::complex<float>> &out) override;

    private:
        std::vector<std::complex<float>> m_delay_line; // ring buffer, size == tap count
        std::size_t m_write_pos = 0;
        std::size_t m_samples_since_output = 0;
    };

} // namespace dsp
